# -*- mode: ruby -*-
# vi: set ft=ruby :
# Lesson 1 Vagrantfile
# This will create a simple three node HAProxy setup
# Author: Robert Freiberger
# Date: 5/2/2018
# License: BSD 
$webscript = <<-SCRIPT
echo '10.0.0.100       haproxy1   haproxy1' >> /etc/hosts
echo '10.0.0.101       web1       web1' >> /etc/hosts
echo '10.0.0.102       web2       web2' >> /etc/hosts
sudo apt-get update -y
sudo apt install nginx -y
sudo systemctl enable nginx
sudo systemctl start nginx
sudo mv /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.old
echo "Welcome to Server:${HOSTINFO}" > /var/www/html/index.html
SCRIPT

$haproxyscript = <<-SCRIPT
echo '10.0.0.100       haproxy1   haproxy1' >> /etc/hosts
echo '10.0.0.101       web1       web1' >> /etc/hosts
echo '10.0.0.102       web2       web2' >> /etc/hosts
sudo apt-get update -y
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get update -y
sudo apt-get install haproxy=1.8.\* -y
sudo cat <<EOT >> /etc/haproxy/haproxy.cfg
frontend myproxy
        bind *:8080
        bind 10.0.0.100:8080
        default_backend mywebservers

backend mywebservers
        server web1 10.0.0.101:80
        server web2 10.0.0.102:80

listen stats
        bind *:8080
        mode  http
        stats enable
        stats uri /stats
        stats auth admin:Password1
EOT
sudo systemctl enable haproxy
sudo systemctl start haproxy
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "haproxyserver" do |haproxyserver|
    haproxyserver.vm.box = "ubuntu/xenial64"
    haproxyserver.vm.hostname = "haproxy1"
    haproxyserver.vm.network "private_network", ip: "10.0.0.100"
    haproxyserver.vm.provider "virtualbox" do |v|
      v.name = "haproxy1"
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--name", "server1"]
    end
    haproxyserver.vm.provision "shell", inline: $haproxyscript
  end

  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/xenial64"
    web1.vm.hostname = "web1"
    web1.vm.network "private_network", ip: "10.0.0.101"
    web1.vm.provider "virtualbox" do |v|
      v.name = "web1"
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--name", "web1"]
    end
    web1.vm.provision "shell", inline: $webscript, \
      env: {"HOSTINFO" => "Web1 - 10.0.0.101"}
  end

  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/xenial64"
    web2.vm.hostname = "web2"
    web2.vm.network "private_network", ip: "10.0.0.102"
    web2.vm.provider "virtualbox" do |v|
      v.name = "web2"
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--name", "web2"]
    end
    web2.vm.provision "shell", inline: $webscript, \
      env: {"HOSTINFO" => "Web2 - 10.0.0.102"}
  end
end
